networks:
  precpago-network:
    driver: bridge

volumes:
  db_data:

services:
  app:
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: precpago
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - precpago-network
    env_file:
      - .env

  nginx:
    image: nginx:stable-alpine
    container_name: precpago-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - precpago-network
