services:
  app:
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: precpago_app
    volumes:
      - .:/var/www
    ports:
      - "8000:9000"
    networks:
      - precpago-network
    depends_on:
      - rabbitmq

  webserver:
    image: nginx:alpine
    container_name: precpago_webserver
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - precpago-network
    depends_on:
      - app

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - precpago-network

networks:
  precpago-network:
    driver: bridge
